### ISSUE TITLE
Installation via script fails on view creation

### ISSUE THREAD

**Issue by pavelpanfilov** [google/shopping_insider#13]
[Shell script](https://github.com/google/shopping_insider?tab=readme-ov-file#222-option-2-install-via-shell-scriptcommand-line) install scenario fails after transfers creation.

Error trace:
```
INFO:root:Creating Shopping Insider specific views.
ERROR:root:Error in sql/5_pmax_criteria_view.sql
Traceback (most recent call last):
  File "/Users/pavel.panfilov/work/repos/shopping_insider/cloud_bigquery.py", line 150, in execute_queries
    query_job.result()
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result
    do_get_result()
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
           ^^^^^^^^
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Unrecognized name: asset_group_listing_group_filter_case_value_product_bidding_category_level; Did you mean asset_group_listing_group_filter_case_value_product_category_level? at [84:11]

Location: US
Job ID: d489f46f-8e37-40d3-809e-4169e2d39ef6

Traceback (most recent call last):
  File "/Users/pavel.panfilov/work/repos/shopping_insider/cloud_env_setup.py", line 146, in <module>
    main()
  File "/Users/pavel.panfilov/work/repos/shopping_insider/cloud_env_setup.py", line 123, in main
    cloud_bigquery.execute_queries(args.project_id, args.dataset_id,
  File "/Users/pavel.panfilov/work/repos/shopping_insider/cloud_bigquery.py", line 150, in execute_queries
    query_job.result()
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result
    do_get_result()
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
           ^^^^^^^^
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Unrecognized name: asset_group_listing_group_filter_case_value_product_bidding_category_level; Did you mean asset_group_listing_group_filter_case_value_product_category_level? at [84:11]

Location: US
Job ID: d489f46f-8e37-40d3-809e-4169e2d39ef6
```

**Comment by pavelpanfilov** [comment]
Hello @phbaudin thx for pushing a fix.

Now facing another error:

```
ERROR:root:Error in sql/5_pmax_criteria_view.sql
Traceback (most recent call last):
  File "/Users/pavel.panfilov/work/repos/shopping_insider/cloud_bigquery.py", line 150, in execute_queries
    query_job.result()
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result
    do_get_result()
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
           ^^^^^^^^
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavel.panfilov/shopping_insider_venv/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Unrecognized name: asset_group_listing_group_filter_case_value_product_bidding_category_id; Did you mean asset_group_listing_group_filter_case_value_product_category_category_id? at [85:22]
```

**Comment by phbaudin** [comment]
Hi Pavel, I fixed this field too and I was able to deploy the solution with this change.

Best,

PH

**Comment by pavelpanfilov** [comment]
Thanks @phbaudin 

I confirm script finished successfully after your [fix](https://github.com/google/shopping_insider/commit/6587766ee507435f2d79d23e31fd7ad081c310b2).
